version: '3.7'

services:

  db:
    image: 'postgres:13'
    ports:
      - "5422:5432"
    container_name: event-manager-db

    environment:
      POSTGRES_DB: event-manager-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 211001

    volumes:
      - ./log-directory:/var/lib/postgresql/data